networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: gbalakrishna/mongodb:v.0.0.1
    container_name: mongodb
    networks:
    - roboshop
  catalogue:
    image: gbalakrishna/catalogue:v.0.0.1
    container_name: catalogue
    networks:
    - roboshop
    depends_on:
    - mongodb
  web:
    image: gbalakrishna/web:v.0.0.1
    container_name: web
    networks:
    - roboshop
    ports:
    - "80:80"
    depends_on:
    - catalogue
