networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: gbalakrishna/mongodb:v.0.0.1
    container_name: mongodb
    networks:
    - roboshop
  catalogue:
    image: gbalakrishna/catalogue:v.0.0.1
    container_name: catalogue
    networks:
    - roboshop
    depends_on:
    - mongodb
  redis:
    image: gbalakrishna/redis:v.0.0.1
    container_name: redis
    networks:
    - roboshop
  user:
    image: gbalakrishna/user:v.0.0.1
    container_name: user
    networks:
    - roboshop
    depends_on:
    - mongodb
    - redis
  cart:
    image: gbalakrishna/cart:v.0.0.1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: gbalakrishna/mysql:v.0.0.1
    container_name: mysql
  web:
    image: gbalakrishna/web:v.0.1.0
    container_name: web
    networks:
    - roboshop
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
